### ISSUE TITLE
Payload too large

### ISSUE THREAD

**Issue by jrpool** [wallyax/wax-dev#2]
I tried to call runWax with the first argument being the HTML content of the `html` element of the home page of IAAP. The outer HTML of that element is a little less than 0.5m characters. Although runWax returned well-formed data when given smaller pages, it responded with a 413 status code (Payload too large) when given that page.

Since web pages these days are often several megabytes in size, if there is a payload size limit it would be good to document that and to advise users how to test pages that are larger than that limit.

**Comment by shritt** [comment]
Hey, @jrpool! In the latest v0.2.0 release we have added the ability to audit an url through runWaxUrl function as shown in the example here - [https://github.com/fsthangaraj/testaro/commit/05bedaf954fbfa32863741607cee55bc3f4aba0f](https://github.com/fsthangaraj/testaro/commit/05bedaf954fbfa32863741607cee55bc3f4aba0f) 
[https://github.com/wallyax/wax-dev#example-usage-for-running-url-audit](https://github.com/wallyax/wax-dev#example-usage-for-running-url-audit)

Hoping you can leverage this for testaro's use case.
